# Site settings
title: "TypeScript PDX"
description: "Staticly Typed JavaScript Is Awesome"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://typescriptpdx.com" # the base hostname & protocol for your site

# Build settings
exclude: []

permalink: /blog/:year/:month/:title

owner_link: http://typescriptpdx.com

domain: typescriptpdx.com

sass:
    sass_dir: _scss